"""
Schemas package
"""
from app.schemas.auth import (
    UserLogin,
    UserRegister,
    TokenResponse,
    PasswordReset,
    PasswordResetConfirm,
    PasswordChange,
)
from app.schemas.user import (
    UserResponse,
    UserCreate,
    UserUpdate,
    UserRoleUpdate,
    APIKeyCreate,
    APIKeyResponse,
    RoleResponse,
)
from app.schemas.analytics import (
    DashboardMetrics,
    RevenueDataPoint,
    ChannelPerformance,
    ProductPerformance,
    StateRevenue,
    PaymentMethodDistribution,
    OrderStatusDistribution,
    CustomerMetrics,
    MarketingMetrics,
    ChannelMarketingPerformance,
    DailyMetricsResponse,
    PinCodeMetricsResponse,
    CODRTOAnalytics,
    InventoryAnalytics,
    SKUProfitability,
    WorkingCapitalMetrics,
    ForecastData,
    FestivalForecast,
    StockoutPrediction,
)
from app.schemas.report import (
    ReportType,
    ReportFormat,
    ReportStatus,
    ScheduleFrequency,
    ReportCreate,
    ReportResponse,
    ReportScheduleCreate,
    ReportScheduleUpdate,
    ReportScheduleResponse,
)
from app.schemas.subscription import (
    SubscriptionPlanResponse,
    SubscriptionCreate,
    SubscriptionResponse,
    SubscriptionUsage,
    InvoiceResponse,
    SubscriptionCancel,
)
from app.schemas.inventory import (
    InventorySnapshotResponse,
    StockAlertResponse,
    DeadStockAnalysis,
    SafetyStockCalculation,
    InventoryTurnoverAnalysis,
)
from app.schemas.marketing import (
    MarketingCampaignResponse,
    AdSpendResponse,
    CampaignPerformance,
    AttributionData,
    CALTVMetrics,
    FacebookAdsSync,
    GoogleAdsSync,
)

__all__ = [
    # Auth
    "UserLogin",
    "UserRegister",
    "TokenResponse",
    "PasswordReset",
    "PasswordResetConfirm",
    "PasswordChange",
    # User
    "UserResponse",
    "UserCreate",
    "UserUpdate",
    "UserRoleUpdate",
    "APIKeyCreate",
    "APIKeyResponse",
    "RoleResponse",
    # Analytics
    "DashboardMetrics",
    "RevenueDataPoint",
    "ChannelPerformance",
    "ProductPerformance",
    "StateRevenue",
    "PaymentMethodDistribution",
    "OrderStatusDistribution",
    "CustomerMetrics",
    "MarketingMetrics",
    "ChannelMarketingPerformance",
    "DailyMetricsResponse",
    "PinCodeMetricsResponse",
    "CODRTOAnalytics",
    "InventoryAnalytics",
    "SKUProfitability",
    "WorkingCapitalMetrics",
    "ForecastData",
    "FestivalForecast",
    "StockoutPrediction",
    # Report
    "ReportType",
    "ReportFormat",
    "ReportStatus",
    "ScheduleFrequency",
    "ReportCreate",
    "ReportResponse",
    "ReportScheduleCreate",
    "ReportScheduleUpdate",
    "ReportScheduleResponse",
    # Subscription
    "SubscriptionPlanResponse",
    "SubscriptionCreate",
    "SubscriptionResponse",
    "SubscriptionUsage",
    "InvoiceResponse",
    "SubscriptionCancel",
    # Inventory
    "InventorySnapshotResponse",
    "StockAlertResponse",
    "DeadStockAnalysis",
    "SafetyStockCalculation",
    "InventoryTurnoverAnalysis",
    # Marketing
    "MarketingCampaignResponse",
    "AdSpendResponse",
    "CampaignPerformance",
    "AttributionData",
    "CALTVMetrics",
    "FacebookAdsSync",
    "GoogleAdsSync",
]
