"""initial migration

Revision ID: 03b728905dc4
Revises: 
Create Date: 2025-11-28 00:40:07.102429+05:30

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b728905dc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hsn_codes',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cgst_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('sgst_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('igst_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hsn_codes_code'), 'hsn_codes', ['code'], unique=True)
    op.create_index(op.f('ix_hsn_codes_id'), 'hsn_codes', ['id'], unique=False)
    op.create_table('ml_models',
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=False),
    sa.Column('training_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('precision', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('recall', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('f1_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('auc_roc', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('mape', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('rmse', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('model_path', sa.String(length=1000), nullable=False),
    sa.Column('model_size_mb', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deployed', sa.Boolean(), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('training_config', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_id'), 'ml_models', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.Enum('ADMIN', 'MANAGER', 'ANALYST', 'FINANCE', name='roletype'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('name', sa.Enum('TRIAL', 'STARTER', 'GROWTH', 'PROFESSIONAL', name='plantype'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('billing_period', sa.String(length=20), nullable=True),
    sa.Column('max_channels', sa.Integer(), nullable=False),
    sa.Column('max_orders_per_month', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('razorpay_plan_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('channels',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel_type', sa.Enum('SHOPIFY', 'WOOCOMMERCE', 'AMAZON', 'FLIPKART', 'MANUAL', name='channeltype'), nullable=False),
    sa.Column('store_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=50), nullable=True),
    sa.Column('auto_sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=True),
    sa.Column('channel_metadata', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_index(op.f('ix_channels_tenant_id'), 'channels', ['tenant_id'], unique=False)
    op.create_table('daily_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('avg_order_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cod_orders', sa.Integer(), nullable=True),
    sa.Column('prepaid_orders', sa.Integer(), nullable=True),
    sa.Column('cod_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('confirmed_orders', sa.Integer(), nullable=True),
    sa.Column('shipped_orders', sa.Integer(), nullable=True),
    sa.Column('delivered_orders', sa.Integer(), nullable=True),
    sa.Column('cancelled_orders', sa.Integer(), nullable=True),
    sa.Column('rto_orders', sa.Integer(), nullable=True),
    sa.Column('rto_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('rto_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('new_customers', sa.Integer(), nullable=True),
    sa.Column('returning_customers', sa.Integer(), nullable=True),
    sa.Column('repeat_purchase_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('total_cogs', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total_profit', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('profit_margin', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('marketing_spend', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('marketing_revenue', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('roas', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cac', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_inventory_value', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('stockout_count', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_metrics_tenant_date', 'daily_metrics', ['tenant_id', 'date'], unique=True)
    op.create_index(op.f('ix_daily_metrics_date'), 'daily_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_daily_metrics_id'), 'daily_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_daily_metrics_tenant_id'), 'daily_metrics', ['tenant_id'], unique=False)
    op.create_table('marketing_campaigns',
    sa.Column('campaign_id', sa.String(length=255), nullable=False),
    sa.Column('campaign_name', sa.String(length=500), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('campaign_metadata', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaign_tenant_channel', 'marketing_campaigns', ['tenant_id', 'channel'], unique=False)
    op.create_index(op.f('ix_marketing_campaigns_id'), 'marketing_campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_marketing_campaigns_tenant_id'), 'marketing_campaigns', ['tenant_id'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('prediction_value', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('confidence_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('actual_value', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('outcome_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prediction_tenant_type', 'ml_predictions', ['tenant_id', 'prediction_type'], unique=False)
    op.create_index(op.f('ix_ml_predictions_id'), 'ml_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_tenant_id'), 'ml_predictions', ['tenant_id'], unique=False)
    op.create_table('pincode_metrics',
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.String(length=10), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('avg_order_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('delivered_orders', sa.Integer(), nullable=True),
    sa.Column('rto_orders', sa.Integer(), nullable=True),
    sa.Column('rto_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('avg_delivery_days', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('cod_orders', sa.Integer(), nullable=True),
    sa.Column('cod_rto_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('last_order_date', sa.Date(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pincode_metrics_tenant_pincode', 'pincode_metrics', ['tenant_id', 'pincode'], unique=True)
    op.create_index(op.f('ix_pincode_metrics_id'), 'pincode_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_pincode_metrics_pincode'), 'pincode_metrics', ['pincode'], unique=False)
    op.create_index(op.f('ix_pincode_metrics_tenant_id'), 'pincode_metrics', ['tenant_id'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('cost_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('selling_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('mrp', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_stock', sa.Integer(), nullable=True),
    sa.Column('safety_stock', sa.Integer(), nullable=True),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.Column('weight', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('length', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('width', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('height', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('hsn_code_id', sa.Integer(), nullable=True),
    sa.Column('tax_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('channel_mappings', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hsn_code_id'], ['hsn_codes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_tenant_sku', 'products', ['tenant_id', 'sku'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('reports',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('report_type', sa.Enum('SALES', 'PRODUCT_PERFORMANCE', 'GST', 'PNL_BY_CHANNEL', 'RTO_ANALYSIS', 'INVENTORY', 'FORECAST', 'MARKETING_PERFORMANCE', name='reporttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='reportstatus'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('file_format', sa.String(length=20), nullable=True),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_tenant_id'), 'reports', ['tenant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIALING', 'PAST_DUE', 'CANCELLED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_orders', sa.Integer(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_customer_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_subscription_id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cod_auto_accept_threshold', sa.Integer(), nullable=True),
    sa.Column('cod_auto_reject_threshold', sa.Integer(), nullable=True),
    sa.Column('rto_cost_percentage', sa.Integer(), nullable=True),
    sa.Column('safety_stock_service_level', sa.Integer(), nullable=True),
    sa.Column('inventory_holding_cost_annual', sa.Integer(), nullable=True),
    sa.Column('tax_enabled', sa.Boolean(), nullable=True),
    sa.Column('tcs_enabled', sa.Boolean(), nullable=True),
    sa.Column('tcs_rate', sa.Integer(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_notifications', sa.Boolean(), nullable=True),
    sa.Column('custom_settings', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_index(op.f('ix_tenant_settings_id'), 'tenant_settings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('ad_spends',
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('spend', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('ctr', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('cpc', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cpa', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('roas', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('attributed_orders', sa.Integer(), nullable=True),
    sa.Column('attributed_revenue', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('ad_metadata', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_adspend_campaign', 'ad_spends', ['campaign_id'], unique=False)
    op.create_index('idx_adspend_tenant_date', 'ad_spends', ['tenant_id', 'date'], unique=False)
    op.create_index(op.f('ix_ad_spends_date'), 'ad_spends', ['date'], unique=False)
    op.create_index(op.f('ix_ad_spends_id'), 'ad_spends', ['id'], unique=False)
    op.create_index(op.f('ix_ad_spends_tenant_id'), 'ad_spends', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('channel_credentials',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_index(op.f('ix_channel_credentials_id'), 'channel_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_channel_credentials_tenant_id'), 'channel_credentials', ['tenant_id'], unique=False)
    op.create_table('cod_remittances',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('remittance_date', sa.Date(), nullable=True),
    sa.Column('expected_remittance_date', sa.Date(), nullable=False),
    sa.Column('settlement_cycle_days', sa.Integer(), nullable=False),
    sa.Column('total_cod_orders', sa.Integer(), nullable=True),
    sa.Column('total_cod_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('remitted_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('pending_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('platform_commission', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('shipping_charges', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cod_charges', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('other_deductions', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_deductions', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('net_remittance', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_delayed', sa.Boolean(), nullable=True),
    sa.Column('delay_days', sa.Integer(), nullable=True),
    sa.Column('alert_sent', sa.Boolean(), nullable=True),
    sa.Column('alert_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cod_remittance_tenant_channel', 'cod_remittances', ['tenant_id', 'channel_id'], unique=False)
    op.create_index(op.f('ix_cod_remittances_channel_id'), 'cod_remittances', ['channel_id'], unique=False)
    op.create_index(op.f('ix_cod_remittances_id'), 'cod_remittances', ['id'], unique=False)
    op.create_index(op.f('ix_cod_remittances_tenant_id'), 'cod_remittances', ['tenant_id'], unique=False)
    op.create_table('inventory_snapshots',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('opening_stock', sa.Integer(), nullable=True),
    sa.Column('closing_stock', sa.Integer(), nullable=True),
    sa.Column('stock_in', sa.Integer(), nullable=True),
    sa.Column('stock_out', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_value', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('days_of_inventory', sa.Integer(), nullable=True),
    sa.Column('turnover_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('forecasted_demand_7d', sa.Integer(), nullable=True),
    sa.Column('forecasted_demand_14d', sa.Integer(), nullable=True),
    sa.Column('forecasted_demand_30d', sa.Integer(), nullable=True),
    sa.Column('predicted_stockout_date', sa.Date(), nullable=True),
    sa.Column('days_until_stockout', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_snapshot_product', 'inventory_snapshots', ['product_id'], unique=False)
    op.create_index('idx_inventory_snapshot_tenant_date', 'inventory_snapshots', ['tenant_id', 'date'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_id'), 'inventory_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_tenant_id'), 'inventory_snapshots', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('razorpay_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('orders',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('external_order_id', sa.String(length=255), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RTO_INITIATED', 'RTO_DELIVERED', 'REFUNDED', name='orderstatus'), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('customer_type', sa.String(length=50), nullable=True),
    sa.Column('shipping_address_line1', sa.String(length=255), nullable=False),
    sa.Column('shipping_address_line2', sa.String(length=255), nullable=True),
    sa.Column('shipping_city', sa.String(length=100), nullable=False),
    sa.Column('shipping_state', sa.String(length=100), nullable=False),
    sa.Column('shipping_pincode', sa.String(length=10), nullable=False),
    sa.Column('shipping_country', sa.String(length=100), nullable=True),
    sa.Column('billing_address_line1', sa.String(length=255), nullable=True),
    sa.Column('billing_address_line2', sa.String(length=255), nullable=True),
    sa.Column('billing_city', sa.String(length=100), nullable=True),
    sa.Column('billing_state', sa.String(length=100), nullable=True),
    sa.Column('billing_pincode', sa.String(length=10), nullable=True),
    sa.Column('billing_country', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.Enum('COD', 'PREPAID', 'UPI', 'CREDIT_CARD', 'DEBIT_CARD', 'NET_BANKING', 'WALLET', name='paymentmethod'), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('shipping_charges', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('tax_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('sgst_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('igst_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('tcs_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cogs', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('platform_fee', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('payment_gateway_fee', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('shipping_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('rto_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('marketing_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('net_profit', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('rto_risk_score', sa.Integer(), nullable=True),
    sa.Column('rto_risk_level', sa.String(length=20), nullable=True),
    sa.Column('rto_probability', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('cod_acceptance_decision', sa.String(length=50), nullable=True),
    sa.Column('cod_manual_override', sa.Boolean(), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('utm_term', sa.String(length=100), nullable=True),
    sa.Column('utm_content', sa.String(length=100), nullable=True),
    sa.Column('gclid', sa.String(length=255), nullable=True),
    sa.Column('fbclid', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_channel', 'orders', ['channel_id'], unique=False)
    op.create_index('idx_order_tenant_date', 'orders', ['tenant_id', 'order_date'], unique=False)
    op.create_index('idx_order_tenant_status', 'orders', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_channel_id'), 'orders', ['channel_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=False)
    op.create_index(op.f('ix_orders_shipping_pincode'), 'orders', ['shipping_pincode'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('variant_attributes', sa.JSON(), nullable=True),
    sa.Column('cost_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('selling_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('mrp', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('weight', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('channel_mappings', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=False)
    op.create_index(op.f('ix_product_variants_tenant_id'), 'product_variants', ['tenant_id'], unique=False)
    op.create_table('report_schedules',
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('report_type', sa.Enum('SALES', 'PRODUCT_PERFORMANCE', 'GST', 'PNL_BY_CHANNEL', 'RTO_ANALYSIS', 'INVENTORY', 'FORECAST', 'MARKETING_PERFORMANCE', name='reporttype'), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('file_format', sa.String(length=20), nullable=True),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_schedules_id'), 'report_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_report_schedules_tenant_id'), 'report_schedules', ['tenant_id'], unique=False)
    op.create_table('stock_alerts',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('STOCKOUT_CRITICAL', 'STOCKOUT_HIGH', 'STOCKOUT_MEDIUM', 'DEAD_STOCK', 'SLOW_MOVING', name='alerttype'), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('recommended_action', sa.String(length=500), nullable=True),
    sa.Column('recommended_quantity', sa.Integer(), nullable=True),
    sa.Column('last_sale_date', sa.Date(), nullable=True),
    sa.Column('days_since_last_sale', sa.Integer(), nullable=True),
    sa.Column('suggested_markdown_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.String(length=1000), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_alerts_id'), 'stock_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_stock_alerts_product_id'), 'stock_alerts', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_alerts_tenant_id'), 'stock_alerts', ['tenant_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('variant_name', sa.String(length=500), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('discount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('tax_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('hsn_code', sa.String(length=8), nullable=True),
    sa.Column('cgst_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('sgst_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('igst_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_tenant_id'), 'order_items', ['tenant_id'], unique=False)
    op.create_table('payment_reconciliations',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('settlement_id', sa.String(length=255), nullable=True),
    sa.Column('platform_order_id', sa.String(length=255), nullable=True),
    sa.Column('system_order_number', sa.String(length=100), nullable=True),
    sa.Column('platform_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('system_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('difference', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('MATCHED', 'MISMATCHED', 'MISSING_IN_PLATFORM', 'MISSING_IN_SYSTEM', 'RESOLVED', name='reconciliationstatus'), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('platform_data', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_recon_tenant_date', 'payment_reconciliations', ['tenant_id', 'settlement_date'], unique=False)
    op.create_index(op.f('ix_payment_reconciliations_channel_id'), 'payment_reconciliations', ['channel_id'], unique=False)
    op.create_index(op.f('ix_payment_reconciliations_id'), 'payment_reconciliations', ['id'], unique=False)
    op.create_index(op.f('ix_payment_reconciliations_order_id'), 'payment_reconciliations', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_reconciliations_tenant_id'), 'payment_reconciliations', ['tenant_id'], unique=False)
    op.create_table('shipments',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('awb_number', sa.String(length=100), nullable=True),
    sa.Column('courier_name', sa.String(length=100), nullable=True),
    sa.Column('courier_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PICKUP_SCHEDULED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', 'RTO', 'CANCELLED', name='shipmentstatus'), nullable=False),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('tracking_url', sa.String(length=500), nullable=True),
    sa.Column('estimated_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declared_weight', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('charged_weight', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('volumetric_weight', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('weight_discrepancy', sa.Boolean(), nullable=True),
    sa.Column('shipping_charge', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cod_charge', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('rto_charge', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_charge', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('pickup_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rto_initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rto_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tracking_events', sa.JSON(), nullable=True),
    sa.Column('shiprocket_shipment_id', sa.String(length=100), nullable=True),
    sa.Column('shiprocket_order_id', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_awb_number'), 'shipments', ['awb_number'], unique=False)
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=True)
    op.create_index(op.f('ix_shipments_tenant_id'), 'shipments', ['tenant_id'], unique=False)
    op.create_table('ndr_reports',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('ndr_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ndr_reason', sa.String(length=255), nullable=False),
    sa.Column('ndr_status', sa.String(length=50), nullable=False),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('action_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_contacted', sa.Boolean(), nullable=True),
    sa.Column('customer_response', sa.Text(), nullable=True),
    sa.Column('reattempt_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ndr_reports_id'), 'ndr_reports', ['id'], unique=False)
    op.create_index(op.f('ix_ndr_reports_shipment_id'), 'ndr_reports', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_ndr_reports_tenant_id'), 'ndr_reports', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ndr_reports_tenant_id'), table_name='ndr_reports')
    op.drop_index(op.f('ix_ndr_reports_shipment_id'), table_name='ndr_reports')
    op.drop_index(op.f('ix_ndr_reports_id'), table_name='ndr_reports')
    op.drop_table('ndr_reports')
    op.drop_index(op.f('ix_shipments_tenant_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_order_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_awb_number'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_payment_reconciliations_tenant_id'), table_name='payment_reconciliations')
    op.drop_index(op.f('ix_payment_reconciliations_order_id'), table_name='payment_reconciliations')
    op.drop_index(op.f('ix_payment_reconciliations_id'), table_name='payment_reconciliations')
    op.drop_index(op.f('ix_payment_reconciliations_channel_id'), table_name='payment_reconciliations')
    op.drop_index('idx_payment_recon_tenant_date', table_name='payment_reconciliations')
    op.drop_table('payment_reconciliations')
    op.drop_index(op.f('ix_order_items_tenant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_stock_alerts_tenant_id'), table_name='stock_alerts')
    op.drop_index(op.f('ix_stock_alerts_product_id'), table_name='stock_alerts')
    op.drop_index(op.f('ix_stock_alerts_id'), table_name='stock_alerts')
    op.drop_table('stock_alerts')
    op.drop_index(op.f('ix_report_schedules_tenant_id'), table_name='report_schedules')
    op.drop_index(op.f('ix_report_schedules_id'), table_name='report_schedules')
    op.drop_table('report_schedules')
    op.drop_index(op.f('ix_product_variants_tenant_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_shipping_pincode'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_channel_id'), table_name='orders')
    op.drop_index('idx_order_tenant_status', table_name='orders')
    op.drop_index('idx_order_tenant_date', table_name='orders')
    op.drop_index('idx_order_channel', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_inventory_snapshots_tenant_id'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_id'), table_name='inventory_snapshots')
    op.drop_index('idx_inventory_snapshot_tenant_date', table_name='inventory_snapshots')
    op.drop_index('idx_inventory_snapshot_product', table_name='inventory_snapshots')
    op.drop_table('inventory_snapshots')
    op.drop_index(op.f('ix_cod_remittances_tenant_id'), table_name='cod_remittances')
    op.drop_index(op.f('ix_cod_remittances_id'), table_name='cod_remittances')
    op.drop_index(op.f('ix_cod_remittances_channel_id'), table_name='cod_remittances')
    op.drop_index('idx_cod_remittance_tenant_channel', table_name='cod_remittances')
    op.drop_table('cod_remittances')
    op.drop_index(op.f('ix_channel_credentials_tenant_id'), table_name='channel_credentials')
    op.drop_index(op.f('ix_channel_credentials_id'), table_name='channel_credentials')
    op.drop_table('channel_credentials')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ad_spends_tenant_id'), table_name='ad_spends')
    op.drop_index(op.f('ix_ad_spends_id'), table_name='ad_spends')
    op.drop_index(op.f('ix_ad_spends_date'), table_name='ad_spends')
    op.drop_index('idx_adspend_tenant_date', table_name='ad_spends')
    op.drop_index('idx_adspend_campaign', table_name='ad_spends')
    op.drop_table('ad_spends')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenant_settings_id'), table_name='tenant_settings')
    op.drop_table('tenant_settings')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_reports_tenant_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index('idx_product_tenant_sku', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_pincode_metrics_tenant_id'), table_name='pincode_metrics')
    op.drop_index(op.f('ix_pincode_metrics_pincode'), table_name='pincode_metrics')
    op.drop_index(op.f('ix_pincode_metrics_id'), table_name='pincode_metrics')
    op.drop_index('idx_pincode_metrics_tenant_pincode', table_name='pincode_metrics')
    op.drop_table('pincode_metrics')
    op.drop_index(op.f('ix_ml_predictions_tenant_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_id'), table_name='ml_predictions')
    op.drop_index('idx_prediction_tenant_type', table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_marketing_campaigns_tenant_id'), table_name='marketing_campaigns')
    op.drop_index(op.f('ix_marketing_campaigns_id'), table_name='marketing_campaigns')
    op.drop_index('idx_campaign_tenant_channel', table_name='marketing_campaigns')
    op.drop_table('marketing_campaigns')
    op.drop_index(op.f('ix_daily_metrics_tenant_id'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_id'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_date'), table_name='daily_metrics')
    op.drop_index('idx_daily_metrics_tenant_date', table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_index(op.f('ix_channels_tenant_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_ml_models_id'), table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_hsn_codes_id'), table_name='hsn_codes')
    op.drop_index(op.f('ix_hsn_codes_code'), table_name='hsn_codes')
    op.drop_table('hsn_codes')
    # ### end Alembic commands ###
